import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./@components/Footer";
import Navbar from "./@components/Navbar";
import "./globals.css";

const getInter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getInter.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
